# Generated by Django 3.1.4 on 2021-03-07 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0002_auto_20210305_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
