# Generated by Django 3.1.4 on 2021-03-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0003_auto_20210307_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='waist',
            field=models.IntegerField(null=True),
        ),
    ]
