# Generated by Django 3.1.4 on 2021-03-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0005_auto_20210309_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='biceps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='chest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
