# Generated by Django 3.1.4 on 2021-03-14 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0006_auto_20210309_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ('date',)},
        ),
    ]
