# Generated by Django 3.1.4 on 2021-03-14 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0007_auto_20210314_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
