# Generated by Django 3.1.4 on 2021-03-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0010_auto_20210314_1508'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.UniqueConstraint(fields=('username', 'date'), name='unique day'),
        ),
    ]
