# Generated by Django 3.1.4 on 2021-03-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0012_auto_20210318_2204'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='measurement',
            name='unique day',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='username',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique day'),
        ),
    ]
